apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run x pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: flaskapp-nginx 
        image: cecilka1337/kubernetes:flaskapp-nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
